title: Tommi Space
email: surfing@tommi.space
description: >-
  A virtual representation of the mess inside Tommi’s mind
baseurl: ""
url: "https://tommi.space"
author:
  name: Tommi
  twitter: xplosionmind
  picture: "https://assets.tommi.space/images/profile.jpg"
logo: "https://assets.tommi.space/logos/favicon.png"
publisher: Tommi
timezone: Europe/Rome
twitter_username: xplosionmind
github_username: xplosionmind
git_repository: "tommi.space"
future: true
profile: true
livereload: true
strict_front_matter: true
images: "https://assets.tommi.space/images"
post-images: "https://assets.tommi.space/images/posts"
assets: "https://assets.tommi.space/assets"
video: "https://assets.tommi.space/video"
audio: "https://assets.tommi.space/audio"
logos: "https://assets.tommi.space/logos"
fonts: "https://assets.tommi.space/fonts"
exclude:
  - riordinare/
  - _notes/private/
  - _notes/templates/
  - _notes/.obsidian
  - _notes/.trash
keep_files:
  - images/
  - assets/
collections:
  poetry:
    output: true
  notes:
    output: true
  filinge:
    output: true
  sconnesso:
    output: true

# CommonMark
# markdown: CommonMark
# commonmark:
#  options: ["FOOTNOTES", "STRIKETHROUGH_DOUBLE_TILDE", "SMART", "VALIDATE_UTF8", "UNSAFE", "LIBERAL_HTML_TAG", "HARDBREAKS"]
#  extensions: ["strikethrough", "table", "tasklist", "autolink", "tagfilter"]

# Pagination
pagination:
  enabled: false
  per_page: 5
  permalink: '/zibaldone/:num/'
  title: ':title :num'

feed:
  path: /feeds/zibaldone.xml
  tags:
    path: /feeds/
    only:
      - geek
  collections:
    poetry:
      path: /feeds/poetry.xml
    filinge:
      path: /feeds/filinge.xml
    notes:
      path: /feeds/jam.xml

# SEO
social:
  name: xplosionmind
tagline: "Tommi's virtual mind"
twitter:
  username: xplosionmind
  card: summary

podcast:
  title: Sconnesso
  description: "Sconnesso è uno pseudo-podcast in cui, per alcuni minuti, racconto ciò che mi sorprende. Sconnesso è sbagliato, ma non scorretto. È atipico, ma non è poi così originale. È curato, ma non studiato alla perfezione. È esasperante, ma mai noioso. È improvvisato, ma non raffazzonato. Non è preparato, ma è attentamente pensato. È confuso e disordinato, ma non complicato. È sconnesso, ma non disconnesso."
  url: "/sconnesso.xml"
  author: "Tommi"
  email: "sono@sconnesso.link"
  link: "https://sconnesso.link"
  logo: "https://assets.tommi.space/images/sconnesso.jpg"
  type: "episodic"
  complete: "yes"
  block: "no"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-target-blank
  - jekyll-watch
  - jekyll-redirect-from
  - jekyll-datapage-generator
  - jekyll-debug
  - jekyll-mentions
  - jekyll-liquify
  - jekyll-auto-image
  - jekyll-email-protect

sass:
  style: compressed
permalink: /:title
defaults:
  -
    scope:
      path: ""
    values:
      layout: "wrapper"
      lang: "en"
      image: "https://assets.tommi.space/images/preview.gif"
      comments: true
      serif: false

  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      lang: it
      excerpt_separator: "<!--more-->"

  -
    scope:
      path: ""
      type: poetry
    values:
      layout: poetry
      lang: it
      permalink: /:title
      primary: "teal"
      description: "Parole disordinate, fra le nuvole e lo spazio"

  -
    scope:
      path: ""
      type: notes
    values:
      layout: jam
      lang: en
      toc: true
      permalink: /:title
      hide: 0

  -
    scope:
      path: ""
      type: sconnesso
    values:
      layout: sconnesso
      lang: it
      permalink: /sconnesso/:title
      primary: "var(--purple)"
      author: "Tommi"
      categories: "sconnesso"
      episodeType: "full"
      explicit: "no"

  -
    scope:
      path: ""
      type: filinge
    values:
      layout: post
      lang: it
      primary: "var(--green)"
      permalink: /filinge/:title