# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: xplosionmind
email: tommiboom+website@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A web version of the mess inside Tommi Boom’s mind
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://xplosionmind.tk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xplosionmind
github_username: xplosionmind
git_repository: xplosionmind
future: true
profile: true
livereload: true
strict_front_matter: true

collections:
  posts:
    layout: "post"
    lang: "it"
    permalink: "/:title"
    excerpt_separator: "<!--more-->"
    redirect_from:
      - "/:date/:title"
      - "/:categories/:title"
      - "/:categories/:date/:title"
  categories:
    output: true
    layout: "category"
  poetry:
    output: true
    layout: "poetry"
    lang: "it"
  stuff:
    output: true
  jar:
    output: true
    layout: "jar"
    permalink: "/:title"
    lang: "en"
    redirect_from: "/:title"
    toc: "true"
  filinge:
    output: true

kramdown:
  syntax_highlighter_opts:
    default_lang: zsh

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-target-blank
  - jekyll-redirect-from

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "wrapper"
      ref: ":title"
      permalink: "/:title"
    
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "it"
      permalink: "/:title"
      excerpt_separator: "<!--more-->"
      redirect_from:
        - "/:date/:title"
        - "/:categories/:title"
        - "/:categories/:date/:title"

  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
      permalink: "/category/:title"

  -
    scope:
      path: ""
      type: "poetry"
    values:
      layout: "poetry"
      lang: "it"
  -
    scope:
      path: "/visioni"
    values:
      image: true
  -
    scope:
      path: ""
      type: "jar"
    values:
      layout: "jar"
      permalink: "/:title"
      lang: "en"
      redirect_from: "/:title"
      toc: "true"

  -
    scope:
      path: ""
      type: "filinge"
    values:
      layout: "post"
      lang: "it"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
 exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
