title: Tommi Space
email: tommiboom@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A web version of the mess inside Tommi Boom’s mind
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tommi.space" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xplosionmind
github_username: xplosionmind
git_repository: "tommi.space"
future: true
profile: true
livereload: true
strict_front_matter: true
exclude:
  - riordinare/
keep_files:
  - images/
  - assets/
collections:
  posts:
    excerpt_separator: "<!--more-->"
  poetry:
    output: true
  jar:
    output: true
  filinge:
    output: true
kramdown:
  syntax_highlighter_opts:
    default_lang: zsh
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-target-blank
  - jekyll-watch
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-admin
sass:
  style: compressed
permalink: /:title
ref: :title
defaults:
  -
    scope:
      path: ""
    values:
      layout: "wrapper"
      ref: ":title"
      lang: "en"
      img: "/images/preview.gif"
      primary: "0"

  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      lang: it
      excerpt_separator: "<!--more-->"

  -
    scope:
      path: ""
      type: poetry
    values:
      layout: poetry
      lang: it
      permalink: /:title
      primary: "teal"

  -
    scope:
      path: ""
      type: jar
    values:
      layout: jar
      lang: en
      toc: 1
      permalink: /:title
      hide: 0

  -
    scope:
      path: ""
      type: filinge
    values:
      layout: post
      lang: it
      primary: "var(--green)"
      permalink: /filinge/:title
