[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # to audit a specific absolute url
  [[plugins.inputs.audits]]
    url = "https://tommi.space/zibaldone"

  # to audit a specific absolute url
  [[plugins.inputs.audits]]
    url = "https://tommi.space/home"

  # to audit a specific absolute url
  [[plugins.inputs.audits]]
    url = "https://tommi.space/stuff"