name: Archive on Wayback Machine

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: tommispace-home
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: tommi.space/home
          saveErrors: true
          saveOutlinks: true
          saveScreenshot: true
      - name: tommispace-tuffo
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: tommi.space/tuffo
          saveErrors: true
          saveOutlinks: true
          saveScreenshot: true
      - name: scambi
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: scambi.org
          saveErrors: true
          saveOutlinks: true
          saveScreenshot: true
      - name: images
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: images.tommi.space
          saveErrors: true
          saveOutlinks: true
          saveScreenshot: true
      - name: sconnesso
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: sconnesso.link
          saveErrors: true
          saveOutlinks: true
          saveScreenshot: true
      - name: sconnesso
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: sconnesso.link
          saveErrors: true
          saveOutlinks: true
          saveScreenshot: true
      - name: quitsocialmedia
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: quitsocialmedia.club/home
          saveErrors: true
          saveOutlinks: true
          saveScreenshot: true
      - name: quitsocialmedia-it
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: quitsocialmedia.club/it/home
          saveErrors: true
          saveOutlinks: true
          saveScreenshot: true
